### ISSUE TITLE
Interceptors don't work with ASP.NET Core 2.1

### ISSUE THREAD

**Issue by marinatord** [unitycontainer/interception#19]
I used the sample code to configure Unity with UseUnityServiceProvider() and ConfigureContainer(IUnityContainer container) in the Startup class. However, the interceptors don't trigger handlers. The same code with interceptors works fine in console applications for both .NET Core and .NET Framework.

The same issue is described here - https://stackoverflow.com/questions/50699219/how-to-use-unity-container-interception-in-asp-net-core-webapi

**Comment by ENikS** [comment]
Interception requires Emit library and as far as I understand is not fully supported in Core apps.
