### ISSUE TITLE
.NetStandard - Interception works 1 level, but not 2 happen again

### ISSUE THREAD

**Issue by otot333** [unitycontainer/interception#24]
i think this issue happen again https://github.com/unitycontainer/interception/commit/e68493659b67e7c466bcb10f12fbdffdf6503a89 in 5.9.1.189 was rollback this code.

**Comment by yfital** [comment]
Indeed it was, I want to solve it for 5.6 and 5.9 as it has too msny breaking changes (FYI, a small changelog for such a large breaking change is appreciated)

**Comment by yfital** [comment]
PR opened:
https://github.com/unitycontainer/interception/pull/25
