### ISSUE TITLE
Is there any docs for interception ?

### ISSUE THREAD

**Issue by GreatFireWall** [unitycontainer/interception#32]

**Comment by ENikS** [comment]
Only the old ones from Microsoft. The library was not changed much and still follows the old API

**Comment by GreatFireWall** [comment]
@ENikS Thanks.

**Comment by GreatFireWall** [comment]
@ENikS Do you know how to make it works with Prism 7.1.0.431 together ?

I had add nuget packet `Unity.Abstractions`, but get same error result:
```
CS0012  C# The type 'IUnityContainer' is defined in an assembly that is not referenced. 
You must add a reference to assembly.
```

![image](https://user-images.githubusercontent.com/4510984/57180776-bde12000-6ebe-11e9-9ca9-bc27672ea50a.png)

![image](https://user-images.githubusercontent.com/4510984/57180787-c6395b00-6ebe-11e9-8a0a-b946424b7bab.png)

**Comment by ENikS** [comment]
You need to ask this question with the Prism team. They control the adoption of the latest.
